---
repository:
  name:                                  "docker-debian11"
  description:                           "Docker debian 11 base image"
  # homepage:                            https://example.github.io/
  topics:                                "debian, docker, testing"
  private:                               false
  has_issues:                            true
  has_projects:                          true
  has_wiki:                              false
  has_downloads:                         true
  default_branch:                        main
  is_template:                           false
  allow_squash_merge:                    true
  allow_merge_commit:                    true
  allow_rebase_merge:                    true
  # Dependabot
  enable_automated_security_fixes:       true
  enable_vulnerability_alerts:           true
branches:
  - name:                                main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews:           true
        require_code_owner_reviews:      false
        dismissal_restrictions:
          users:                         []
          teams:                         []
      required_status_checks:
        strict:                          true
        contexts:                        [ "sample" ]
      enforce_admins:                    true
      required_linear_history:           true
      restrictions:
        apps:                            []
        users:                           []
        teams:                           []
